# Generated by Django 2.1.4 on 2018-12-30 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_firstname', models.CharField(max_length=50)),
                ('cust_lastname', models.CharField(max_length=50)),
                ('cust_phonenumber', models.CharField(max_length=50)),
                ('cust_country', models.CharField(max_length=50)),
                ('cust_state', models.CharField(max_length=50)),
                ('cust_city', models.CharField(max_length=50)),
                ('cust_address', models.CharField(max_length=200)),
                ('cust_passport_number', models.CharField(max_length=100)),
                ('cust_checkin_date', models.DateTimeField(verbose_name='checkin')),
                ('cust_checkout_date', models.DateTimeField(verbose_name='checkout')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.CharField(max_length=50)),
                ('room_name', models.CharField(max_length=50)),
                ('room_pin', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkin.Room'),
        ),
    ]
