# Generated by Django 2.1.4 on 2018-12-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_id',
            new_name='room_sid',
        ),
    ]
