# Generated by Django 2.1.4 on 2018-12-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20181230_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_sid',
            new_name='room_snum',
        ),
    ]
